#!/bin/bash



### Find Colors From .Xresources ###
xrdb ~/.Xresources

findcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}



findcolors


### Config BSP Workspaces ###

### Or Use Monitor Name , You Can Find It With "bspc query -M --names" ###
# bspc monitor LVDS1 -d I II III IV V VI 
# bspc monitor -d I II III IV V VI VII VIII


bspc monitor LVDS1 -d I II III IV V VI 


#bspc config focus_follows_pointer true
#bspc config border_width         2
#bspc config window_gap           8  
#bspc config split_ratio          0.50 

#bspc config borderless_monocle true
#bspc config gapless_monocle true
#bspc config paddingless_monocle true
#bspc config single_monocle false
#bspc config focus_follows_pointer true

#bspc config focused_border_color "$BLUE" 
#bspc config normal_border_color "$BACKGROUND"
#bspc config active_border_color "$MAGENTA"
#bspc config presel_feedback_color "$GREEN"


bspc config focus_follows_pointer true
bspc config border_width         2
bspc config window_gap           8  
bspc config split_ratio          0.50 
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config top_padding 32
bspc config right_padding 8
bspc config bottom_padding 8
bspc config left_padding 8
bspc config focused_border_color "$BACKGROUND"
bspc config normal_border_color "#$BACKGROUND"

### My Rules###

bspc rule -a St-float state=floating follow=on focus=on
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a Zathura state=tiled



### My Autostart ###

killall -9 sxhkd  dunst polybar 

dunst \
-geom "280x50-10+38" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &


picom --config ~/.config/picom/picom.conf --experimental-backends &

sxhkd &

$HOME/BSPWM-Project/Polybar-Testing/launch.sh &

feh  --no-fehbg --bg-scale $HOME/Wallpapers/202.jpg

numlockx on

setxkbmap -option caps:backspace


### Cursor ###

xsetroot -cursor_name left_ptr


xset r rate 200 25




sleep 0.9
notify-send "Bspwm Loaded" 



